import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { auth } from '@/auth';
import PublicHeader from '@/components/layouts/PublicHeader';
import PrivateHeader from '@/components/layouts/PrivateHeader';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <>
      {session?.user?.email ? <PrivateHeader /> : <PublicHeader />}
      {children}
    </>
  );
}
