import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { auth } from '@/auth';
import { PublicFooter } from '@/components/layouts/PublicFooter';
import { PublicHeader } from '@/components/layouts/PublicHeader';
import { PrivateHeader } from '@/components/layouts/PrivateHeader';
import { WrapLayout } from '@/components/layouts/WrapLayout';
import { Main } from '@/components/layouts/Main';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <WrapLayout>
      {session?.user?.email ? <PrivateHeader /> : <PublicHeader />}
      <Main>{children}</Main>
      <PublicFooter />
    </WrapLayout>
  );
}
